In [6]:
import math
import numpy as np

In [13]:
# Array sum 
a = np.array([16, 12, 6, 10, 11])
b = np.array([8, 12, 14, 9, 9])

c = a + b

print(c.sum())
print(c)

107
[24 24 20 19 20]


In [14]:
# Hamanard product
a = np.array([11, 20, 10, 10, 7])
b = np.array([11, 16, 9, 10, 11])

c = a * b
print(c)
print(c.sum())

[121 320  90 100  77]
708


In [18]:
# Matrices sum
a = np.array(
   [[9,  14, 11,  6,  4],
    [13, 12, 21,  2, 13],
    [12, 15, 16,  5, 11],
    [12, 11, 9,   9,  7],
    [10, 10, 12,  3,  8]])

b = np.array(
   [[7,  7,  6,  7, 10],
    [6, 15, 10, 16,  8],
    [8,  9, 13,  7, 16],
    [10, 7, 11, 15, 13],
    [5,  7, 13,  9, 10]])

c = a + b
print(c)
print(c.sum())

[[16 21 17 13 14]
 [19 27 31 18 21]
 [20 24 29 12 27]
 [22 18 20 24 20]
 [15 17 25 12 18]]
500


In [19]:
# Arrays subtraction
a = np.array([5, 10, 15, 2, 7])
b = np.array([10, 3, 13, 5, 11])

c = a - b

print(c.sum())
print(c)

-3
[-5  7  2 -3 -4]


In [20]:
# Array and scalar product
a = np.array([9, 16, 6, 8, 8])
alpha = 13

c = alpha * a

print(c.sum())
print(c)

611
[117 208  78 104 104]


In [21]:
# Matrices subtraction
a = np.array(
   [[16,  11,    9,   10,    9],
    [11,  16,    9,    3,   10],
    [8,   10,   12,    7,    6],
    [12,  10,   12,    9,   10],
    [4,    9,   10,    4,   11]])

b = np.array(
   [[3,    10,   14,    7,    9],
    [9,     6,    9,   12,    9],
    [12,    8,   17,   11,   10],
    [14,   11,    9,   14,   10],
    [16,   15,    8,   10,   15]])

c = a - b
print(c)
print(c.sum())

[[ 13   1  -5   3   0]
 [  2  10   0  -9   1]
 [ -4   2  -5  -4  -4]
 [ -2  -1   3  -5   0]
 [-12  -6   2  -6  -4]]
-30


In [23]:
# Matrices product
a = np.array(
   [[11,  12,    6,   20,    9],
    [9,   11,   16,   10,   13],
    [13,  10,   11,   11,    9],
    [11,  10,   15,    9,    1],
    [6,    5,   15,   12,    6]])

b = np.array(
   [[16,   11,   12,    9,   11],
    [2,    11,    8,    6,   17],
    [9,    10,    9,   15,    8],
    [5,    15,   14,    8,   13],
    [9,     5,    7,    7,   10]])

c = a @ b

print(c)
print(c.sum())

[[435 658 625 484 723]
 [477 595 571 558 674]
 [463 573 552 493 634]
 [385 521 480 463 538]
 [355 481 457 447 487]]
13129


In [30]:
# Matrix and scalar product
a = np.matrix([[13,   8,    7,   15,   14],
               [9,    8,    6,   11,    7],
               [5,   10,    9,   14,   14],
               [4,    5,   12,    7,    9],
               [9,    9,   10,   12,    9]])
alpha = 3

c = alpha * a

print(c.sum())
print(c)

708
[[39 24 21 45 42]
 [27 24 18 33 21]
 [15 30 27 42 42]
 [12 15 36 21 27]
 [27 27 30 36 27]]
